[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
tinyvec = "1.8.0"

[[bench]]
name = "day1"
harness = false

[[bench]]
name = "day2"
harness = false
